In [75]:
import pandas as pd


df = pd.read_csv(r'C:\Users\Gabriel\Documents\Main_Python\new\personal_finance_app\bd\extrato_bancario_base.csv')

df

,date,description,amount,type,channel,counterparty,currency,account_name,account_number,institution,running_balance
0,2025-05-01,Farmácia Popular,-271.90,DEBIT,PIX,Farmácia Popular,BRL,Conta Corrente,1234-***-9,Banco Exemplo S.A.,2228.10
1,2025-05-03,Faculdade UERJ,-40.32,DEBIT,Boleto,Faculdade UERJ,BRL,Conta Corrente,1234-***-9,Banco Exemplo S.A.,2187.78
2,2025-05-03,Padaria Central,-33.57,DEBIT,PIX,Padaria Central,BRL,Conta Corrente,1234-***-9,Banco Exemplo S.A.,2154.21
3,2025-05-03,Academia Fit+,-117.13,DEBIT,Saque,Academia Fit+,BRL,Conta Corrente,1234-***-9,Banco Exemplo S.A.,2037.08
4,2025-05-04,Transferência Fulano,292.09,CREDIT,App,Transferência Fulano,BRL,Conta Corrente,1234-***-9,Banco Exemplo S.A.,2329.17
...,...,...,...,...,...,...,...,...,...,...,...
121,2025-07-27,Faculdade UERJ,-22.51,DEBIT,Saque,Faculdade UERJ,BRL,Conta Corrente,1234-***-9,Banco Exemplo S.A.,-250.71
122,2025-07-28,Restaurante Sabor & Cia,-177.66,DEBIT,Cartão Crédito,Restaurante Sabor & Cia,BRL,Conta Corrente,1234-***-9,Banco Exemplo S.A.,-428.37
123,2025-07-28,Restaurante Sabor & Cia,-48.32,DEBIT,Cartão Crédito,Restaurante Sabor & Cia,BRL,Conta Corrente,1234-***-9,Banco Exemplo S.A.,-476.69
124,2025-07-30,TIM Fatura,-102.88,DEBIT,Saque,TIM Fatura,BRL,Conta Corrente,1234-***-9,Banco Exemplo S.A.,-579.57
125,2025-07-30,Padaria Lisboa,-73.89,DEBIT,Cartão Débito,Padaria Lisboa,BRL,Conta Corrente,1234-***-9,Banco Exemplo S.A.,-653.46

In [85]:
df_counterparty = df[['counterparty','amount']]
grouped_df = df_counterparty.groupby('counterparty').sum()
sorted_df = df_counterparty.sort_values('amount',ascending=True)
grouped_df.head(), sorted_df.head()

(                    amount
 counterparty
 99 *Corrida         -40.22
 Academia Fit+      -410.00
 Banco Exemplo S.A.  -51.60
 CEDAE              -266.10
 Cedae              -409.85,
              counterparty   amount
 6    Imobiliária Boa Casa -1800.00
 38   Imobiliária Boa Casa -1800.00
 87   Imobiliária Boa Casa -1800.00
 108    Laboratório Exames  -523.20
 90         Faculdade UERJ  -486.34)

In [ ]:
descricoes = df['description']

most_commom_counterparty = df['counterparty'].mode()[0]

descricoes

0             Farmácia Popular
1               Faculdade UERJ
2              Padaria Central
3                Academia Fit+
4         Transferência Fulano
                ...
121             Faculdade UERJ
122    Restaurante Sabor & Cia
123    Restaurante Sabor & Cia
124                 TIM Fatura
125             Padaria Lisboa
Name: description, Length: 126, dtype: object

In [80]:
biggest_credit_amount = float(sorted_df.iloc[-1].amount)
biggest_credit_counterparty = str(sorted_df.iloc[-1].counterparty)
biggest_credit_counterparty, biggest_credit_amount

('Empresa XYZ LTDA', 5200.0)

In [81]:
biggest_debit_amount = float(sorted_df.iloc[0].amount)
biggest_debit_counterparty = str(sorted_df.iloc[0].counterparty)


biggest_debit_counterparty, biggest_debit_amount

('Imobiliária Boa Casa', -1800.0)